services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: amiqus-ats-app
        container_name: amiqus_app
        volumes:
            - .:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - mysql
        ports:
            - "8000:80"
            - "5173:5173" # Vite dev server
        working_dir: /var/www
        command: bash -c "php artisan serve --host=0.0.0.0 --port=80"

    mysql:
        image: mysql:8
        container_name: amiqus_mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: amiqus
            MYSQL_USER: amiqus
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
